### ISSUE TITLE
TODO before final sprint review

### ISSUE THREAD

**Issue by dingepfl** [SwengGolfTeam/Sweng_Golf#214]
- [x] Check bug with location (on creating an offer, removing the location before it was finished loading): We probably simply need to add an initial value to the variable so we avoid the `NullPointerException` when the listener hasn't completed yet.
- [x] Complete `README.md` with what can be done with the app
- [x] Set a limitation on messages length to prevent users writing infinite length messages that could potentially make the app crash
- [x] Modify the name of fragments
- [x] Modify the name of preferences to favorite
- [x] Take a look at Lint issues and fix them
- [x] Remove forgotten TODOs

**Comment by ejolles** [comment]
for the third point I think that a limit of 140 characters as twitter limit can be a good idea

**Comment by ElsaWeb** [comment]
Yes I talked about it with Robin and Sébastien this morning and I wanted to change it on my branch but it got merge before I knew it. Maybe 140 is not enough, but 280 characters? We just want to prevent thousands and thousands of characters, maybe even 1000 is ok, what do you think?

**Comment by SFulpius** [comment]
I think 1000 is ok. As Elsa said, we want to prevent the people from sending infinite long data to the server, not to communicate.
